src/AgnusCrm.UI.Web/Controllers/Adminlte/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace lte.Controllers
{
    public partial class AdminlteController : Controller
    {
        public IActionResult Top()
        {
            return View();
        }

        public IActionResult Boxed()
        {
            return View();
        }

        public IActionResult Fixed()
        {
            return View();
        }

        public IActionResult Collapsed()
        {
            return View();
        }
    }
}

src/AgnusCrm.UI.Web/Controllers/PriceListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgnusCrm.Data;
using AgnusCrm.Models;
using Microsoft.AspNetCore.Http;
using AgnusCrm.Models.PriceList;

namespace AgnusCrm.Controllers
{
    public class PriceListController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PriceListController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PriceList
        public async Task<IActionResult> Index()
        {
            var searchString = "camera";
            ViewData["PriceType"] = "PVP1";

            ViewData["Family"] = new SelectList(_context.Family, "code", "description");
            ViewData["SubFamily"] = new SelectList(_context.SubFamily, "code", "description");
            ViewData["Brand"] = new SelectList(_context.Brand, "code", "description");


            if (!String.IsNullOrEmpty(searchString))
            {
                var priceList = _context.Product
                    //.Include(p => p.Brand)
                    //.Include(p => p.Family)
                    //.Include(p => p.SubFamily)
                    //.Include(p => p.ProductPrice)
                    .Where(s => (s.productCode.Contains(searchString) ||
                    s.description.Contains(searchString)) );

                return View(await priceList.ToListAsync());

            }
            else
            {
                var priceList = _context.Product;
                    //.Include(p => p.Brand)
                    //.Include(p => p.Family)
                    //.Include(p => p.SubFamily)
                    //.Include(p => p.ProductPrice)
                    //.Where(s => s.stock > 0)

                return View(await priceList.ToListAsync());
            }

        }

        [HttpPost]
        public async Task<IActionResult> Index(string searchString,
            [Bind("listBrand,listFamily,listSubFamily")] ViewSearchPriceList price,
            IFormCollection form)
        {

            ViewData["PriceType"] = "PVP1";

            ViewData["Family"] = new SelectList(_context.Family, "code", "description");
            ViewData["SubFamily"] = new SelectList(_context.SubFamily, "code", "description");
            ViewData["Brand"] = new SelectList(_context.Brand, "code", "description");

            string filtroBrand = "";
            string filtroFamily = "";
            string filtroSubFamily = "";

            if (price.listBrand != null)
            {
                filtroBrand = "";

                foreach (var item in price.listBrand)
                {
                    filtroBrand += filtroBrand.Length == 0 ? "'" + item + "'" : ",'" + item + "'";
                }

                filtroBrand = "and B.code in (" + filtroBrand + ") ";
            }

            if (price.listFamily != null)
            {
                filtroFamily = "";

                foreach (var item in price.listFamily)
                {
                    filtroFamily += filtroFamily.Length == 0 ? "'" + item + "'" : ",'" + item + "'";
                }

                filtroFamily = "and F.code in (" + filtroFamily + ") ";
            }

            if (price.listSubFamily != null)
            {
                filtroSubFamily = "";

                foreach (var item in price.listSubFamily)
                {
                    filtroSubFamily += filtroSubFamily.Length == 0 ? "'" + item + "'" : ",'" + item + "'";
                }

                filtroSubFamily = "and SF.Code in (" + filtroSubFamily + ") ";
            }

            string sql = string.Format( @"select P.id, isnull(b.description,'') as brand_desc, isnull(f.description,'') as family_desc, 
	            isnull(sf.description,'') as subFamily_desc, p.[desc],p.stock,pp.pvp1 as price, CONVERT(Bit,0) as encomenda
                from dbo.Product P
                inner join dbo.Family F on F.code = p.familycode {0}
                inner join dbo.SubFamily SF on SF.id = p.subFamilyCode {1}
                inner join dbo.Brand B on B.code = p.brandCode {2}
                inner join dbo.ProductPrice pp on pp.product = p.id
                where p.stock > 0"
                , filtroFamily,filtroSubFamily,filtroBrand
            );

            var priceList = _context.ViewPriceList.FromSql(sql);

            return View(await priceList.ToListAsync());
            
        }
        // GET: PriceList/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var view_PriceList = await _context.View_PriceList
                .FirstOrDefaultAsync(m => m.artigo == id);
            if (view_PriceList == null)
            {
                return NotFound();
            }

            return View(view_PriceList);
        }

        // GET: PriceList/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PriceList/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("artigo,marca,marca_Desc,familia,familia_Desc,subFamilia,subFamilia_Desc,artigo_Desc,preco,stock")] View_PriceList view_PriceList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(view_PriceList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(view_PriceList);
        }

        // GET: PriceList/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var view_PriceList = await _context.View_PriceList.FindAsync(id);
            if (view_PriceList == null)
            {
                return NotFound();
            }
            return View(view_PriceList);
        }

        // POST: PriceList/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("artigo,marca,marca_Desc,familia,familia_Desc,subFamilia,subFamilia_Desc,artigo_Desc,preco,stock")] View_PriceList view_PriceList)
        {
            if (id != view_PriceList.artigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(view_PriceList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!View_PriceListExists(view_PriceList.artigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(view_PriceList);
        }

        // GET: PriceList/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var view_PriceList = await _context.View_PriceList
                .FirstOrDefaultAsync(m => m.artigo == id);
            if (view_PriceList == null)
            {
                return NotFound();
            }

            return View(view_PriceList);
        }

        // POST: PriceList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var view_PriceList = await _context.View_PriceList.FindAsync(id);
            _context.View_PriceList.Remove(view_PriceList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool View_PriceListExists(string id)
        {
            return _context.View_PriceList.Any(e => e.artigo == id);
        }
    }
}

src/AgnusCrm.UI.Web/Views/Shared/_AdminlteNetcoreBasicScripts.cshtml
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
</environment>

<!-- DataTables -->
<script src="~/lib/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="~/lib/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="~/lib/AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="~/lib/AdminLTE/bower_components/fastclick/lib/fastclick.js"></script>
<!-- Select2 -->
<script src="~/lib/AdminLTE/bower_components/select2/dist/js/select2.full.min.js"></script>
<!-- InputMask -->
<script src="~/lib/AdminLTE/plugins/input-mask/jquery.inputmask.js"></script>
<script src="~/lib/AdminLTE/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
<script src="~/lib/AdminLTE/plugins/input-mask/jquery.inputmask.extensions.js"></script>
<!-- date-range-picker -->
<script src="~/lib/AdminLTE/bower_components/moment/min/moment.min.js"></script>
<script src="~/lib/AdminLTE/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- bootstrap datepicker -->
<script src="~/lib/AdminLTE/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<!-- bootstrap color picker -->
<script src="~/lib/AdminLTE/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<!-- bootstrap time picker -->
<script src="~/lib/AdminLTE/plugins/timepicker/bootstrap-timepicker.min.js"></script>
<!-- SlimScroll -->
<script src="~/lib/AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- iCheck 1.0.1 -->
<script src="~/lib/AdminLTE/plugins/iCheck/icheck.min.js"></script>
<!-- FastClick -->
<script src="~/lib/AdminLTE/bower_components/fastclick/lib/fastclick.js"></script>

<script src="~/lib/AdminLTE/dist/js/adminlte.js"></script>
<script>
    var AdminLTEOptions = {
        //Enable sidebar expand on hover effect for sidebar mini
        //This option is forced to true if both the fixed layout and sidebar mini
        //are used together
        sidebarExpandOnHover: true,
        //BoxRefresh Plugin
        enableBoxRefresh: true,
        //Bootstrap.js tooltip
        enableBSToppltip: true
    };
</script>

<script src="~/js/site.js" asp-append-version="true"></script>




@*<!-- jQuery 3 -->
    <script src="~/adminlte/components/jquery/dist/jquery.min.js"></script>
    <!--jqueryUI-->
    <script src="~/lib/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Select2 -->
    <script src="~/adminlte/components/select2/dist/js/select2.full.min.js"></script>
    <!-- bootstrap datepicker -->
    <script src="~/adminlte/components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- PACE -->
    <script src="~/adminlte/components/PACE/pace.min.js"></script>
    <!-- Slimscroll -->
    <script src="~/adminlte/components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/adminlte/components/fastclick/lib/fastclick.js"></script>
    <!-- DataTables -->
    <script src="~/adminlte/components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/adminlte/components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <!-- Toastr -->
    <script src="~/lib/toastr/toastr.min.js"></script>
    <!-- Sweetalert -->
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <!-- Site -->
    <script src="~/js/site.min.js"></script>
    <!-- Serialize JSON -->
    <script src="~/lib/marioizquierdo-jquery.serializeJSON/jquery.serializejson.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/adminlte/dist/js/demo.js"></script>*@

src/AgnusCrm.UI.Web/Views/Shared/_AdminlteNetcoreBasicStyles.cshtml
@*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
<link href="~/lib/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

<!-- Font Awesome -->
<link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />
<link href="~/lib/font-awesome/css/brands.css" rel="stylesheet" />
<link href="~/lib/font-awesome/css/solid.css" rel="stylesheet" />

<!-- Ionicons -->
<link href="~/lib/AdminLTE/bower_components/Ionicons/css/ionicons.min.css" rel="stylesheet" />
<!-- DataTables -->
<link rel="stylesheet" href="~/lib/AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

<!-- daterange picker -->
<link rel="stylesheet" href="~/lib/AdminLTE/bower_components/bootstrap-daterangepicker/daterangepicker.css">
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="~/lib/AdminLTE/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="~/lib/AdminLTE/plugins/iCheck/all.css">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet" href="~/lib/AdminLTE/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">
<!-- Bootstrap time Picker -->
<link rel="stylesheet" href="~/lib/AdminLTE/plugins/timepicker/bootstrap-timepicker.min.css">
<!-- Select2 -->
<link rel="stylesheet" href="~/lib/AdminLTE/bower_components/select2/dist/css/select2.min.css">

<!-- Pace style -->
<link rel="stylesheet" href="~/lib/adminlte/plugins/pace/pace.min.css">

<!-- Theme style -->
<link rel="stylesheet" href="~/lib/Adminlte/dist/css/AdminLTE.min.css">
<link href="~/lib/AdminLTE/dist/css/skins/_all-skins.css" rel="stylesheet" />
<link rel="stylesheet" href="~/css/main.css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Google Font -->
<link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

src/AgnusCrm.UI.Web/Views/Shared/_AdminlteNetcoreFooter.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2018 <a href="/">CRM PLUS INVENTORY</a>.</strong> All rights
    reserved.
</footer>

src/AgnusCrm.UI.Web/Views/Shared/_AdminlteNetcorePopup.cshtml
@{
    Layout = null;
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Add / Edit Data</h4>
</div>
<form onsubmit="return SubmitAddEdit(this)">
    <div class="box-body">
        @RenderBody()
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>


@Html.Partial("_AdminlteAgnusCrmBasicStyles")

@RenderSection("Styles", required: false)

@Html.Partial("_AdminlteAgnusCrmBasicScripts")

@RenderSection("Scripts", required: false)

src/AgnusCrm.UI.Web/Views/Shared/_SideBar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{

    ApplicationUser appUser = await UserManager.GetUserAsync(User);

}   

<div class="main-sidebar">
    <!-- Inner sidebar -->
    <div class="sidebar">
        <!-- user panel (Optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/lib/AdminLTE/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />

            </div>
            <div class="pull-left info">
                <p>@User.Identity.Name</p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div><!-- /.user-panel -->
        <!-- Search Form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form><!-- /.sidebar-form -->

        

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu tree" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="treeview">
                <a href="/">
                    <i class="fa fa-tachometer-alt"></i> <span>Dashboard</span>

                </a>

            </li>

            @if (User.IsInRole("admin"))
            {

                <li class="">
                    <a asp-controller="PriceList" asp-action="Index">
                        <i class="fa fa-money"></i>
                        <span>Price List</span>
                    </a>

                </li>
                <li class="active">
                    <a href="widgets.html">
                        <i class="fa fa-th"></i> <span>Widgets</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-green">new</small>
                        </span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-pie-chart"></i>
                        <span>Charts</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu" style="display: none;">
                        <li><a href="charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
                        <li><a href="charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
                        <li><a href="charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
                        <li><a href="charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-laptop"></i>
                        <span>UI Elements</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu" style="display: none;">
                        <li><a href="UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
                        <li><a href="UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
                        <li><a href="UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
                        <li><a href="UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
                        <li><a href="UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
                        <li><a href="UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-edit"></i> <span>Forms</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu" style="display: none;">
                        <li><a href="forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
                        <li><a href="forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                        <li><a href="forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-table"></i> <span>Tables</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu" style="display: none;">
                        <li><a href="tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                        <li><a href="tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
                    </ul>
                </li>
                <li>
                    <a href="calendar.html">
                        <i class="fa fa-calendar"></i> <span>Calendar</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-red">3</small>
                            <small class="label pull-right bg-blue">17</small>
                        </span>
                    </a>
                </li>
                <li>
                    <a href="mailbox/mailbox.html">
                        <i class="fa fa-envelope"></i> <span>Mailbox</span>
                        <span class="pull-right-container">
                            <small class="label pull-right bg-yellow">12</small>
                            <small class="label pull-right bg-green">16</small>
                            <small class="label pull-right bg-red">5</small>
                        </span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-folder"></i> <span>Examples</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu" style="display: none;">
                        <li><a href="examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
                        <li><a href="examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
                        <li><a href="examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
                        <li><a href="examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
                        <li><a href="examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                        <li><a href="examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                        <li><a href="examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                        <li><a href="examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                        <li><a href="examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-share"></i> <span>Multilevel</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu" style="display: none;">
                        <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                        <li class="treeview menu-open">
                            <a href="#">
                                <i class="fa fa-circle-o"></i> Level One
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu" style="display: block;">
                                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                                <li class="treeview menu-open">
                                    <a href="#">
                                        <i class="fa fa-circle-o"></i> Level Two
                                        <span class="pull-right-container">
                                            <i class="fa fa-angle-left pull-right"></i>
                                        </span>
                                    </a>
                                    <ul class="treeview-menu" style="display: block;">
                                        <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                        <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
                    </ul>
                </li>
                <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
                <li class="header">LABELS</li>
                <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
                <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
                <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>

            }

            @if (User.IsInRole("ApplicationUser"))
            {
                <li id="menuCustomer" class="">
                    <a asp-controller="Customers" asp-action="Index">
                        <i class="fa fa-user-tie"></i>
                        <span>Customers</span>
                    </a>

                </li>
            }

        </ul><!-- /.sidebar-menu -->

    </div><!-- /.sidebar -->
</div>
<!-- /.main-sidebar -->